-- Add short_name column to ai_generated_models table
-- This column stores a short, English filename generated by Claude API
-- Used for archive display and GCode filenames

ALTER TABLE public.ai_generated_models
ADD COLUMN IF NOT EXISTS short_name VARCHAR(50);

-- Add comment for documentation
COMMENT ON COLUMN public.ai_generated_models.short_name IS 'Claude API로 생성된 짧은 영문 이름 (아카이브 표시 및 GCode 파일명용)';

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_ai_generated_models_short_name
ON public.ai_generated_models(short_name);
